### ISSUE TITLE
Create the MVP of the Lesson Maker

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#16]
#### Description

Following the wireframe and visual design, we need to code Lesson Maker which is the MVP for the Teach feature of our app. 
#### Tools Needed

HTML, CSS, JQuery, Bootstrap
#### Wireframes

![htc_teachmvp_072613](https://f.cloud.github.com/assets/3219885/866279/33430126-f664-11e2-8540-f0126a5f336b.jpg)
![htc_teachmvp_0726132](https://f.cloud.github.com/assets/3219885/866280/365e7408-f664-11e2-8370-cbba8539ea49.jpg)
#### Visual Design

![bizfriendly_teachmvp_072613](https://f.cloud.github.com/assets/3219885/866281/47da07f6-f664-11e2-9af9-8336a8374678.gif)

**Comment by ondrae** [comment]
Working on this in the 'teach' branch.

**Comment by ondrae** [comment]
Todo still for the Teach page:
- [ ] Choose between [jQuery Draggable](jqueryui.com/draggable/‎) or [HTML5 Draggable](https://developer.mozilla.org/en-US/docs/DragDrop/Drag_and_Drop). jQuery seems simpler at first pass.
- [ ] Additional layout and UX pass.
- [ ] Implement Preview function.
- [ ] Connect lesson builder to the Database.

**Comment by ardouglass** [comment]
If adding jQuery UI isn't a problem, jQuery Draggable is the option I'd recommend. Everything I've read, heard, and experienced before giving up the drag and drop aspect of things at hackathons suggests that [the HTML5 spec should be thrown out for being so terrible](http://www.quirksmode.org/blog/archives/2009/09/the_html5_drag.html).

It also looks like you'd want to implement sortable behavior since the lessons appear to be one column wide, and jQuery UI makes that part easy too.

**Comment by arielkennan** [comment]
Celebration icons: 
![star](https://f.cloud.github.com/assets/3219885/921461/9437d4b4-fef9-11e2-86b0-8542bc73a37a.gif)
![flag](https://f.cloud.github.com/assets/3219885/921463/97d632d2-fef9-11e2-8a88-9306a28ffac3.gif)
![heart](https://f.cloud.github.com/assets/3219885/921464/9c777512-fef9-11e2-95cc-ce734c923e1e.gif)
![thumbsup](https://f.cloud.github.com/assets/3219885/921465/a9e263b0-fef9-11e2-8cdf-e18fbd112e40.gif)

**Comment by arielkennan** [comment]
![teachicon_gray](https://f.cloud.github.com/assets/3219885/941542/367769f0-0149-11e3-958b-85be2a8717ef.gif)
